-- plugins that use default config with no further calls get set up here
require("bufferline").setup()
require("Comment").setup()
require("glow").setup()
require('leap').add_default_mappings()
require("lualine").setup()
require('mkdnflow').setup({})
require("nvim-surround").setup()
require("shade").setup()
require("which-key").setup()
